# v3.800.20
# https://virtocommerce.atlassian.net/browse/VCST-4203
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.20    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}