# v3.800.24
# https://virtocommerce.atlassian.net/browse/VCST-4487
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.24    
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}